name: build

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types:
      - published

env:
  UV_SYSTEM_PYTHON: 1

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - run: uv pip install --upgrade pre-commit
      - run: pre-commit run --all-files

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - run: uv sync
      - run: python -m unittest
        working-directory: ./tests

  test_msv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - uses: actions/setup-python@v5
        with:
          python-version: 3.8
          cache: pip
      - run: uv sync --resolution lowest-direct
      - run: python -m unittest
        working-directory: ./tests

  codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - run: uv sync --extra coverage
      - run: pytest --cov --cov-report=xml
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  publish:
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/oxrdflib
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - run: uv pip install build
      - run: python -m build --sdist --wheel --outdir dist/ .
      - uses: pypa/gh-action-pypi-publish@release/v1
